"""

----------------------------------------
Water Quality Monitoring Software  
(HydroQual Prime) - Version 1.0.1  
----------------------------------------

Developed by: Amirreza Nemati Mansour  
Specialized in: Python, Qt, and Water Engineering Applications  
Contact: amirreza.nemati@ut.ac.ir(mailto:amirreza.nemati@ut.ac.ir)  

This software is designed to analyze water quality data efficiently and accurately.  
It features advanced statistical analysis, interactive visualization tools, and an intuitive UI  
for a seamless user experience in water quality assessment.  

© 2025 Amirreza Nemati Mansour. All rights reserved.  

"""


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_calc_index_window(object):
    def setupUi(self, calc_index_window):
        calc_index_window.setObjectName("calc_index_window")
        calc_index_window.resize(502, 573)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(calc_index_window.sizePolicy().hasHeightForWidth())
        calc_index_window.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/images/main_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        calc_index_window.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(calc_index_window)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(calc_index_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.index_comboBox = QtWidgets.QComboBox(calc_index_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.index_comboBox.sizePolicy().hasHeightForWidth())
        self.index_comboBox.setSizePolicy(sizePolicy)
        self.index_comboBox.setDuplicatesEnabled(False)
        self.index_comboBox.setObjectName("index_comboBox")
        self.index_comboBox.addItem("")
        self.index_comboBox.addItem("")
        self.index_comboBox.addItem("")
        self.index_comboBox.addItem("")
        self.index_comboBox.addItem("")
        self.index_comboBox.addItem("")
        self.index_comboBox.addItem("")
        self.index_comboBox.addItem("")
        self.index_comboBox.addItem("")
        self.index_comboBox.addItem("")
        self.index_comboBox.addItem("")
        self.index_comboBox.addItem("")
        self.index_comboBox.addItem("")
        self.index_comboBox.addItem("")
        self.index_comboBox.addItem("")
        self.horizontalLayout.addWidget(self.index_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.index_listWidget = QtWidgets.QListWidget(calc_index_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.index_listWidget.sizePolicy().hasHeightForWidth())
        self.index_listWidget.setSizePolicy(sizePolicy)
        self.index_listWidget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.index_listWidget.setObjectName("index_listWidget")
        self.verticalLayout.addWidget(self.index_listWidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.removeItem_index_pushButton = QtWidgets.QPushButton(calc_index_window)
        self.removeItem_index_pushButton.setObjectName("removeItem_index_pushButton")
        self.horizontalLayout_4.addWidget(self.removeItem_index_pushButton)
        self.label_2 = QtWidgets.QLabel(calc_index_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(calc_index_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.indexBrowse_pushButton = QtWidgets.QPushButton(calc_index_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indexBrowse_pushButton.sizePolicy().hasHeightForWidth())
        self.indexBrowse_pushButton.setSizePolicy(sizePolicy)
        self.indexBrowse_pushButton.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.indexBrowse_pushButton.setObjectName("indexBrowse_pushButton")
        self.horizontalLayout_3.addWidget(self.indexBrowse_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.index_tableWidget = QtWidgets.QTableWidget(calc_index_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.index_tableWidget.sizePolicy().hasHeightForWidth())
        self.index_tableWidget.setSizePolicy(sizePolicy)
        self.index_tableWidget.setMaximumSize(QtCore.QSize(16777215, 75))
        self.index_tableWidget.setObjectName("index_tableWidget")
        self.index_tableWidget.setColumnCount(0)
        self.index_tableWidget.setRowCount(0)
        self.index_tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.index_tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.verticalLayout.addWidget(self.index_tableWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(calc_index_window)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.index_startCalc_pushButton = QtWidgets.QPushButton(calc_index_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.index_startCalc_pushButton.sizePolicy().hasHeightForWidth())
        self.index_startCalc_pushButton.setSizePolicy(sizePolicy)
        self.index_startCalc_pushButton.setObjectName("index_startCalc_pushButton")
        self.horizontalLayout_2.addWidget(self.index_startCalc_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_6 = QtWidgets.QLabel(calc_index_window)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.export_index_tableWidget = QtWidgets.QTableWidget(calc_index_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.export_index_tableWidget.sizePolicy().hasHeightForWidth())
        self.export_index_tableWidget.setSizePolicy(sizePolicy)
        self.export_index_tableWidget.setObjectName("export_index_tableWidget")
        self.export_index_tableWidget.setColumnCount(0)
        self.export_index_tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.export_index_tableWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(calc_index_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.export_index_pushButton = QtWidgets.QPushButton(calc_index_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.export_index_pushButton.sizePolicy().hasHeightForWidth())
        self.export_index_pushButton.setSizePolicy(sizePolicy)
        self.export_index_pushButton.setObjectName("export_index_pushButton")
        self.horizontalLayout_5.addWidget(self.export_index_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(calc_index_window)
        QtCore.QMetaObject.connectSlotsByName(calc_index_window)

    def retranslateUi(self, calc_index_window):
        _translate = QtCore.QCoreApplication.translate
        calc_index_window.setWindowTitle(_translate("calc_index_window", "Water Quality index Calculator"))
        self.label_4.setText(_translate("calc_index_window", "Select Water Quality Index:"))
        self.index_comboBox.setItemText(0, _translate("calc_index_window", "select index"))
        self.index_comboBox.setItemText(1, _translate("calc_index_window", "British Columbia Water Quality Index"))
        self.index_comboBox.setItemText(2, _translate("calc_index_window", "Drinking Water Quality Index"))
        self.index_comboBox.setItemText(3, _translate("calc_index_window", "Groundwater Quality Index"))
        self.index_comboBox.setItemText(4, _translate("calc_index_window", "Irish Water Quality Index"))
        self.index_comboBox.setItemText(5, _translate("calc_index_window", "Iran Water Quality Index"))
        self.index_comboBox.setItemText(6, _translate("calc_index_window", "Canadian Water Quality Index"))
        self.index_comboBox.setItemText(7, _translate("calc_index_window", "Liou Pollution Index"))
        self.index_comboBox.setItemText(8, _translate("calc_index_window", "Langelier Saturation Index"))
        self.index_comboBox.setItemText(9, _translate("calc_index_window", "Heavy Metal Pollution Index"))
        self.index_comboBox.setItemText(10, _translate("calc_index_window", "National Sanitation Foundation Water Quality Index(USA)"))
        self.index_comboBox.setItemText(11, _translate("calc_index_window", "Organ Index"))
        self.index_comboBox.setItemText(12, _translate("calc_index_window", "PoS Index"))
        self.index_comboBox.setItemText(13, _translate("calc_index_window", "Weighted Arithmetic Water Quality Index"))
        self.index_comboBox.setItemText(14, _translate("calc_index_window", "Water Quality Index"))
        self.removeItem_index_pushButton.setText(_translate("calc_index_window", "remove item"))
        self.label.setText(_translate("calc_index_window", "Import Water Quality Standards:"))
        self.indexBrowse_pushButton.setText(_translate("calc_index_window", "Browse "))
        self.index_startCalc_pushButton.setText(_translate("calc_index_window", "Start Calculation"))
        self.label_6.setText(_translate("calc_index_window", "Result:"))
        self.export_index_pushButton.setText(_translate("calc_index_window", "Export table"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    calc_index_window = QtWidgets.QWidget()
    ui = Ui_calc_index_window()
    ui.setupUi(calc_index_window)
    calc_index_window.show()
    sys.exit(app.exec_())
