"""

----------------------------------------
Water Quality Monitoring Software  
(HydroQual Prime) - Version 1.0.1  
----------------------------------------

Developed by: Amirreza Nemati Mansour  
Specialized in: Python, Qt, and Water Engineering Applications  
Contact: amirreza.nemati@ut.ac.ir(mailto:amirreza.nemati@ut.ac.ir)  

This software is designed to analyze water quality data efficiently and accurately.  
It features advanced statistical analysis, interactive visualization tools, and an intuitive UI  
for a seamless user experience in water quality assessment.  

© 2025 Amirreza Nemati Mansour. All rights reserved.  

"""

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(957, 575)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(50, 50))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/images/main_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setAutoScrollMargin(16)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setRowCount(20)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(40)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(33, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(34, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(35, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(36, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(37, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(38, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(39, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(60)
        self.horizontalLayout.addWidget(self.tableWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setAutoFillBackground(False)
        self.toolBar.setStyleSheet("background-color:#f5f5f5")
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 957, 21))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuSave = QtWidgets.QMenu(self.menubar)
        self.menuSave.setObjectName("menuSave")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSample_data = QtWidgets.QMenu(self.menubar)
        self.menuSample_data.setObjectName("menuSample_data")
        self.menuCharge_balance_error1 = QtWidgets.QMenu(self.menuSample_data)
        self.menuCharge_balance_error1.setObjectName("menuCharge_balance_error1")
        self.menuDraw_Diagram1 = QtWidgets.QMenu(self.menuSample_data)
        self.menuDraw_Diagram1.setObjectName("menuDraw_Diagram1")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionClear_Data = QtWidgets.QAction(MainWindow)
        self.actionClear_Data.setObjectName("actionClear_Data")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.toolbar_new = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolbar_new.setIcon(icon1)
        self.toolbar_new.setObjectName("toolbar_new")
        self.toolbar_add_data = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolbar_add_data.setIcon(icon2)
        self.toolbar_add_data.setObjectName("toolbar_add_data")
        self.toolbar_save = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolbar_save.setIcon(icon3)
        self.toolbar_save.setObjectName("toolbar_save")
        self.toolbar_chart = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/chart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolbar_chart.setIcon(icon4)
        self.toolbar_chart.setObjectName("toolbar_chart")
        self.toolbar_delete_row = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("resources/icons/delete_row.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolbar_delete_row.setIcon(icon5)
        self.toolbar_delete_row.setObjectName("toolbar_delete_row")
        self.toolbar_statistics = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("resources/icons/statistics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolbar_statistics.setIcon(icon6)
        self.toolbar_statistics.setObjectName("toolbar_statistics")
        self.toolbar_clear_table = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("resources/icons/clear_table.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolbar_clear_table.setIcon(icon7)
        self.toolbar_clear_table.setObjectName("toolbar_clear_table")
        self.toolbar_ckeckAnalyze = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("resources/icons/check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap("icons/check.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolbar_ckeckAnalyze.setIcon(icon8)
        self.toolbar_ckeckAnalyze.setObjectName("toolbar_ckeckAnalyze")
        self.toolbar_drawDiagram = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("resources/icons/chart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolbar_drawDiagram.setIcon(icon9)
        self.toolbar_drawDiagram.setObjectName("toolbar_drawDiagram")
        self.toolbar_WQI = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("resources/icons/index.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolbar_WQI.setIcon(icon10)
        self.toolbar_WQI.setObjectName("toolbar_WQI")
        self.actionResource_Base = QtWidgets.QAction(MainWindow)
        self.actionResource_Base.setObjectName("actionResource_Base")
        self.actionEvapotranspiration = QtWidgets.QAction(MainWindow)
        self.actionEvapotranspiration.setObjectName("actionEvapotranspiration")
        self.actionAgricultural_Services = QtWidgets.QAction(MainWindow)
        self.actionAgricultural_Services.setObjectName("actionAgricultural_Services")
        self.actionWithdrawal = QtWidgets.QAction(MainWindow)
        self.actionWithdrawal.setObjectName("actionWithdrawal")
        self.actionSurface_Water = QtWidgets.QAction(MainWindow)
        self.actionSurface_Water.setObjectName("actionSurface_Water")
        self.actionGroundwater = QtWidgets.QAction(MainWindow)
        self.actionGroundwater.setObjectName("actionGroundwater")
        self.actionCalendar = QtWidgets.QAction(MainWindow)
        self.actionCalendar.setObjectName("actionCalendar")
        self.actionBase_name = QtWidgets.QAction(MainWindow)
        self.actionBase_name.setObjectName("actionBase_name")
        self.actionDownload_Raster = QtWidgets.QAction(MainWindow)
        self.actionDownload_Raster.setObjectName("actionDownload_Raster")
        self.actionManage_Layers = QtWidgets.QAction(MainWindow)
        self.actionManage_Layers.setObjectName("actionManage_Layers")
        self.actionTolerance = QtWidgets.QAction(MainWindow)
        self.actionTolerance.setObjectName("actionTolerance")
        self.actionaddrow = QtWidgets.QAction(MainWindow)
        self.actionaddrow.setObjectName("actionaddrow")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.toolbar_Scenarios = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/scenarios.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolbar_Scenarios.setIcon(icon11)
        self.toolbar_Scenarios.setObjectName("toolbar_Scenarios")
        self.actionAdd_layer = QtWidgets.QAction(MainWindow)
        self.actionAdd_layer.setObjectName("actionAdd_layer")
        self.actionTool_Box = QtWidgets.QAction(MainWindow)
        self.actionTool_Box.setObjectName("actionTool_Box")
        self.actionCalendar_2 = QtWidgets.QAction(MainWindow)
        self.actionCalendar_2.setObjectName("actionCalendar_2")
        self.actionBase_Name = QtWidgets.QAction(MainWindow)
        self.actionBase_Name.setObjectName("actionBase_Name")
        self.actionDownload_Raster_2 = QtWidgets.QAction(MainWindow)
        self.actionDownload_Raster_2.setObjectName("actionDownload_Raster_2")
        self.actionManage_Layers_2 = QtWidgets.QAction(MainWindow)
        self.actionManage_Layers_2.setObjectName("actionManage_Layers_2")
        self.actionTolerance_2 = QtWidgets.QAction(MainWindow)
        self.actionTolerance_2.setObjectName("actionTolerance_2")
        self.actionSheet_1 = QtWidgets.QAction(MainWindow)
        self.actionSheet_1.setObjectName("actionSheet_1")
        self.actionSheet_2 = QtWidgets.QAction(MainWindow)
        self.actionSheet_2.setObjectName("actionSheet_2")
        self.actionSheet_3 = QtWidgets.QAction(MainWindow)
        self.actionSheet_3.setObjectName("actionSheet_3")
        self.actionSheet_4 = QtWidgets.QAction(MainWindow)
        self.actionSheet_4.setObjectName("actionSheet_4")
        self.actionSheet_5 = QtWidgets.QAction(MainWindow)
        self.actionSheet_5.setObjectName("actionSheet_5")
        self.actionSheet_6 = QtWidgets.QAction(MainWindow)
        self.actionSheet_6.setObjectName("actionSheet_6")
        self.actionTotal = QtWidgets.QAction(MainWindow)
        self.actionTotal.setObjectName("actionTotal")
        self.toolbar_AddRow = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("resources/icons/add_row.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolbar_AddRow.setIcon(icon12)
        self.toolbar_AddRow.setObjectName("toolbar_AddRow")
        self.actiondescriptivestatistics = QtWidgets.QAction(MainWindow)
        self.actiondescriptivestatistics.setObjectName("actiondescriptivestatistics")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionload = QtWidgets.QAction(MainWindow)
        self.actionload.setObjectName("actionload")
        self.actionImport_data = QtWidgets.QAction(MainWindow)
        self.actionImport_data.setObjectName("actionImport_data")
        self.actionimport_sample_data = QtWidgets.QAction(MainWindow)
        self.actionimport_sample_data.setObjectName("actionimport_sample_data")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionDelete_row = QtWidgets.QAction(MainWindow)
        self.actionDelete_row.setObjectName("actionDelete_row")
        self.actionClear_table = QtWidgets.QAction(MainWindow)
        self.actionClear_table.setObjectName("actionClear_table")
        self.actionWater_quality_index = QtWidgets.QAction(MainWindow)
        self.actionWater_quality_index.setObjectName("actionWater_quality_index")
        self.actionCharge_balance_error = QtWidgets.QAction(MainWindow)
        self.actionCharge_balance_error.setObjectName("actionCharge_balance_error")
        self.action5_threshold = QtWidgets.QAction(MainWindow)
        self.action5_threshold.setCheckable(True)
        self.action5_threshold.setChecked(True)
        self.action5_threshold.setObjectName("action5_threshold")
        self.action10_threshold = QtWidgets.QAction(MainWindow)
        self.action10_threshold.setCheckable(True)
        self.action10_threshold.setObjectName("action10_threshold")
        self.actionDraw_Diagram = QtWidgets.QAction(MainWindow)
        self.actionDraw_Diagram.setObjectName("actionDraw_Diagram")
        self.actionShow_institute_logo_on_charts = QtWidgets.QAction(MainWindow)
        self.actionShow_institute_logo_on_charts.setCheckable(True)
        self.actionShow_institute_logo_on_charts.setObjectName("actionShow_institute_logo_on_charts")
        self.toolBar.addAction(self.toolbar_add_data)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.toolbar_statistics)
        self.toolBar.addAction(self.toolbar_clear_table)
        self.toolBar.addAction(self.toolbar_ckeckAnalyze)
        self.toolBar.addAction(self.toolbar_delete_row)
        self.toolBar.addAction(self.toolbar_AddRow)
        self.toolBar.addAction(self.toolbar_WQI)
        self.toolBar.addAction(self.toolbar_drawDiagram)
        self.menuAbout.addAction(self.actionHelp)
        self.menuAbout.addAction(self.actionAbout)
        self.menuSave.addAction(self.actionImport_data)
        self.menuSave.addAction(self.actionimport_sample_data)
        self.menuSave.addSeparator()
        self.menuSave.addAction(self.actionSave_as)
        self.menuSave.addAction(self.actionload)
        self.menuHelp.addAction(self.actionaddrow)
        self.menuHelp.addAction(self.actionDelete_row)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionClear_table)
        self.menuCharge_balance_error1.addAction(self.actionCharge_balance_error)
        self.menuCharge_balance_error1.addSeparator()
        self.menuCharge_balance_error1.addAction(self.action5_threshold)
        self.menuCharge_balance_error1.addAction(self.action10_threshold)
        self.menuDraw_Diagram1.addAction(self.actionDraw_Diagram)
        self.menuDraw_Diagram1.addAction(self.actionShow_institute_logo_on_charts)
        self.menuSample_data.addAction(self.actiondescriptivestatistics)
        self.menuSample_data.addAction(self.menuCharge_balance_error1.menuAction())
        self.menuSample_data.addAction(self.actionWater_quality_index)
        self.menuSample_data.addAction(self.menuDraw_Diagram1.menuAction())
        self.menubar.addAction(self.menuSave.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuSample_data.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HydroQual Prime"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sample"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "EC"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "TDS"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "pH"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Ca"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Mg"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Na"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "K"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "HCO3"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "CO3"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Cl"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "SO4"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "DO"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "BOD"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "TEMP"))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "TRAN"))
        item = self.tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "TON"))
        item = self.tableWidget.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "MRP"))
        item = self.tableWidget.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "DIN"))
        item = self.tableWidget.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "NO3"))
        item = self.tableWidget.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "As"))
        item = self.tableWidget.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "Hg"))
        item = self.tableWidget.horizontalHeaderItem(22)
        item.setText(_translate("MainWindow", "Pb"))
        item = self.tableWidget.horizontalHeaderItem(23)
        item.setText(_translate("MainWindow", "Cd"))
        item = self.tableWidget.horizontalHeaderItem(24)
        item.setText(_translate("MainWindow", "Ni"))
        item = self.tableWidget.horizontalHeaderItem(25)
        item.setText(_translate("MainWindow", "NH4"))
        item = self.tableWidget.horizontalHeaderItem(26)
        item.setText(_translate("MainWindow", "Cr"))
        item = self.tableWidget.horizontalHeaderItem(27)
        item.setText(_translate("MainWindow", "Mn"))
        item = self.tableWidget.horizontalHeaderItem(28)
        item.setText(_translate("MainWindow", "PO4"))
        item = self.tableWidget.horizontalHeaderItem(29)
        item.setText(_translate("MainWindow", "Fe"))
        item = self.tableWidget.horizontalHeaderItem(30)
        item.setText(_translate("MainWindow", "FC"))
        item = self.tableWidget.horizontalHeaderItem(31)
        item.setText(_translate("MainWindow", "TC"))
        item = self.tableWidget.horizontalHeaderItem(32)
        item.setText(_translate("MainWindow", "COD"))
        item = self.tableWidget.horizontalHeaderItem(33)
        item.setText(_translate("MainWindow", "TSS"))
        item = self.tableWidget.horizontalHeaderItem(34)
        item.setText(_translate("MainWindow", "TRUB"))
        item = self.tableWidget.horizontalHeaderItem(35)
        item.setText(_translate("MainWindow", "B"))
        item = self.tableWidget.horizontalHeaderItem(36)
        item.setText(_translate("MainWindow", "Fl"))
        item = self.tableWidget.horizontalHeaderItem(37)
        item.setText(_translate("MainWindow", "Al"))
        item = self.tableWidget.horizontalHeaderItem(38)
        item.setText(_translate("MainWindow", "Cu"))
        item = self.tableWidget.horizontalHeaderItem(39)
        item.setText(_translate("MainWindow", "Zn"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.menuSave.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Edit"))
        self.menuSample_data.setTitle(_translate("MainWindow", "Analysis"))
        self.menuCharge_balance_error1.setTitle(_translate("MainWindow", "Charge balance error"))
        self.menuDraw_Diagram1.setTitle(_translate("MainWindow", "Draw Diagram"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File"))
        self.actionClear_Data.setText(_translate("MainWindow", "Tool Box"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.toolbar_new.setText(_translate("MainWindow", "open_file"))
        self.toolbar_new.setToolTip(_translate("MainWindow", "Open File"))
        self.toolbar_add_data.setText(_translate("MainWindow", "add_data"))
        self.toolbar_add_data.setToolTip(_translate("MainWindow", "Import data"))
        self.toolbar_save.setText(_translate("MainWindow", "save"))
        self.toolbar_save.setToolTip(_translate("MainWindow", "Save"))
        self.toolbar_chart.setText(_translate("MainWindow", "chart"))
        self.toolbar_chart.setToolTip(_translate("MainWindow", "Show Chart"))
        self.toolbar_delete_row.setText(_translate("MainWindow", "delete_row"))
        self.toolbar_delete_row.setToolTip(_translate("MainWindow", "Delete row"))
        self.toolbar_statistics.setText(_translate("MainWindow", "statistics"))
        self.toolbar_statistics.setToolTip(_translate("MainWindow", "descriptive statistics"))
        self.toolbar_clear_table.setText(_translate("MainWindow", "clear table"))
        self.toolbar_clear_table.setToolTip(_translate("MainWindow", "Clear Table"))
        self.toolbar_ckeckAnalyze.setText(_translate("MainWindow", "ckeck_analyze"))
        self.toolbar_ckeckAnalyze.setToolTip(_translate("MainWindow", "Charge balance error"))
        self.toolbar_drawDiagram.setText(_translate("MainWindow", "drawDiagram"))
        self.toolbar_drawDiagram.setToolTip(_translate("MainWindow", "Draw Diagram"))
        self.toolbar_WQI.setText(_translate("MainWindow", "water_quality_index_toolbar"))
        self.toolbar_WQI.setToolTip(_translate("MainWindow", "water quality index"))
        self.actionResource_Base.setText(_translate("MainWindow", "Resource Base"))
        self.actionEvapotranspiration.setText(_translate("MainWindow", "Evapotranspiration"))
        self.actionAgricultural_Services.setText(_translate("MainWindow", "Agricultural Services"))
        self.actionWithdrawal.setText(_translate("MainWindow", "Withdrawal"))
        self.actionSurface_Water.setText(_translate("MainWindow", "Surface Water"))
        self.actionGroundwater.setText(_translate("MainWindow", "Groundwater"))
        self.actionCalendar.setText(_translate("MainWindow", "Calendar"))
        self.actionBase_name.setText(_translate("MainWindow", "Base Name"))
        self.actionDownload_Raster.setText(_translate("MainWindow", "Download Raster"))
        self.actionManage_Layers.setText(_translate("MainWindow", "Manage Layers"))
        self.actionTolerance.setText(_translate("MainWindow", "Tolerance"))
        self.actionaddrow.setText(_translate("MainWindow", "Add row"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.toolbar_Scenarios.setText(_translate("MainWindow", "Scenarios"))
        self.toolbar_Scenarios.setToolTip(_translate("MainWindow", "Scenarios"))
        self.actionAdd_layer.setText(_translate("MainWindow", "Add layer"))
        self.actionTool_Box.setText(_translate("MainWindow", "Tool Box"))
        self.actionCalendar_2.setText(_translate("MainWindow", "Calendar"))
        self.actionBase_Name.setText(_translate("MainWindow", "Base Name"))
        self.actionDownload_Raster_2.setText(_translate("MainWindow", "Download Raster"))
        self.actionManage_Layers_2.setText(_translate("MainWindow", "Tolerance"))
        self.actionTolerance_2.setText(_translate("MainWindow", "Tolerance"))
        self.actionSheet_1.setText(_translate("MainWindow", "Sheet 1"))
        self.actionSheet_2.setText(_translate("MainWindow", "Sheet 2"))
        self.actionSheet_3.setText(_translate("MainWindow", "Sheet 3"))
        self.actionSheet_4.setText(_translate("MainWindow", "Sheet 4"))
        self.actionSheet_5.setText(_translate("MainWindow", "Sheet 5"))
        self.actionSheet_6.setText(_translate("MainWindow", "Sheet 6"))
        self.actionTotal.setText(_translate("MainWindow", "Total"))
        self.toolbar_AddRow.setText(_translate("MainWindow", "Add Row"))
        self.toolbar_AddRow.setToolTip(_translate("MainWindow", "Add row table"))
        self.actiondescriptivestatistics.setText(_translate("MainWindow", "Descriptive statistics"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionload.setText(_translate("MainWindow", "Load"))
        self.actionImport_data.setText(_translate("MainWindow", "Import data ..."))
        self.actionimport_sample_data.setText(_translate("MainWindow", "Sample data"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionDelete_row.setText(_translate("MainWindow", "Delete row"))
        self.actionClear_table.setText(_translate("MainWindow", "Clear table"))
        self.actionWater_quality_index.setText(_translate("MainWindow", "Water quality index"))
        self.actionCharge_balance_error.setText(_translate("MainWindow", "Charge balance error"))
        self.action5_threshold.setText(_translate("MainWindow", "5% threshold"))
        self.action10_threshold.setText(_translate("MainWindow", "10% threshold"))
        self.actionDraw_Diagram.setText(_translate("MainWindow", "Draw Diagram"))
        self.actionShow_institute_logo_on_charts.setText(_translate("MainWindow", "Show institute logo on charts"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
